### ISSUE TITLE
好用！期待支持vue2.0

### ISSUE THREAD

**Issue by beeplin** [surmon-china/vue-touch-ripple#1]

**Comment by surmon-china** [comment]
很快支持，感谢！

**Comment by surmon-china** [comment]
已兼容至支持Vue.js全版本

**Comment by beeplin** [comment]
为什么限定非行内元素呢？想要给按钮加ripple，结果按钮变成了块元素，页面都错位了，而且ripple效果变成了横跨页面的一长条。

**Comment by surmon-china** [comment]
实际上不会的，建议非行内元素使用，是因为，在使用directive模式时，组件会给所对应元素内部append<div>子节点，如果是p、tr、img、Input...将会失效，所以刚才所述的单标签或者一些特殊的不允许内部插入元素的元素，在使用时需使用component方式

**Comment by surmon-china** [comment]
但是使用component方式，组件会在外层自动包裹div，div默认是block的，可以通过给组件加class来用css改变其成为指定的盒子类型，如：

``` html
<touch-ripple class="inline">
   <button>it's a button</button>
</touch-ripple>
```

``` css
.inline {
  display: inline-block;
}
```
