### ISSUE TITLE
报错 Uncaught ReferenceError: component is not defined

### ISSUE THREAD

**Issue by liudianliang** [surmon-china/vue-touch-ripple#11]
import VueTouchRipple from 'vue-touch-ripple'
Vue.use(VueTouchRipple);
以指令的形式使用，昨天还可以，今天报错了，

**Comment by liudianliang** [comment]
startRipple is not defined
以组件的形式使用报这个错误，在家里都没问题，在公司怎么都不行

**Comment by surmon-china** [comment]
所以组件和指令两种使用形式都会发生错误吗？

**Comment by surmon-china** [comment]
错误需要截出图或者将实际错误代码复制过来，具体对应到错误所在的行。
BTW：这些问题没有人会比当事人更有可能解决。

**Comment by liudianliang** [comment]
这个可能是版本问题

>  node v
v6.9.5

> npm -v
3.10.10
这个对node版本有要求吗

**Comment by liudianliang** [comment]
不是版本的问题，我升级了一下谷歌浏览器就ok了，具体什么原因就不清楚了
