### ISSUE TITLE
[important] Touch Ripple don't works with the latest vue-loader

### ISSUE THREAD

**Issue by throrin19** [surmon-china/vue-touch-ripple#12]
With the latest vue Loader version `12.0.x`, the touch-ripple don't works correctly :

![peek 17-05-2017 09-57](https://cloud.githubusercontent.com/assets/1394778/26143961/5e545952-3ae7-11e7-85ca-aadeaf173b59.gif)

With the previous version, it works fine. After research I find the problem. In the `12.0.0` it was a "small breaking change" :

> Upgrading vue-style-loader to 3.0 introduces a small breaking change: the CSS contained in a *.vue component will now be lazy-injected, when the component is rendered for the first time. (Previously the style is injected as soon as the component is imported.)

And after other researchs, I find this post to show how to fix that : https://forum.vuejs.org/t/overriding-child-component-classes-with-vue-loader-12-0-0/10369

**Comment by surmon-china** [comment]
Thanks for your feedback! i will solve it!

**Comment by surmon-china** [comment]
Hi, I do not know what kind of change I can make to make him work better, can you give some advice?

**Comment by throrin19** [comment]
In my case, I force the use of previous version of vue-loader. I think you should see that directly with them :disappointed:

**Comment by throrin19** [comment]
Oh yes, I remove the vue component, I import directly the css on my project and I inject classes directly on targeted element.  With this method, the vue-touch-ripple works fine with the latest vue-loader

**Comment by ChobitsSP** [comment]
build style to single css file

**Comment by Reedo0910** [comment]
是的，我也遇到了这个问题，用的是directive模式，vue-loader版本是最新的12.1.x 
刚嵌入代码时能正常运行，但是刷新浏览器之后就只剩下元素高度改变，没有动画效果，也没有报错。
尝试修改了一下css选择器无果，最后把你的js和CSS样式提出来，在我的组件内引用js和css就正常了。无奈😂
