### ISSUE TITLE
为什么我用的是点击之后才波浪, 长按是没有波浪的,松开之后才有

### ISSUE THREAD

**Issue by liqingxi1116** [surmon-china/vue-touch-ripple#18]
是本来就是这样的,还是我的有问题

**Comment by liqingxi1116** [comment]
发现是因为在移动端就是这样的,     pc端没有问题,  没有兼容移动端吗

**Comment by surmon-china** [comment]
因为在移动端使用`touch`事件会出现异常，所以用的 `click` 事件，而`click`事件有`200-300ms`的延时，且必须手指抬起才生效。

**Comment by daleiyinsi** [comment]
那能解决吗,   移动端手机必须抬起才生效,  感觉体验很不好

**Comment by liqingxi1116** [comment]
@surmon-china 那能解决吗, 移动端手机必须抬起才生效, 感觉体验很不好

**Comment by zWingz** [comment]
我觉得可以在动画完毕后直接清空..不用等到mouseup或者touchend.

**Comment by surmon-china** [comment]
其实是合理的，我测试过 Material Design 的标准实现，和现在是一样的。
