### ISSUE TITLE
元素消失不正常的问题

### ISSUE THREAD

**Issue by LiuChangkang** [surmon-china/vue-touch-ripple#19]
IOS 11.2.2上的Safari浏览器，波纹退出的时候没有过渡，直接消失。

**Comment by surmon-china** [comment]
那就是不支持 C3 喽，还能有啥办法

**Comment by LiuChangkang** [comment]
全局添加下面的样式后可以正常过渡
.ripple-core {
    transition-duration: .5s, .4s;
  }
