### ISSUE TITLE
火狐浏览器外层点击事件@click无效

### ISSUE THREAD

**Issue by lizhenggan** [surmon-china/vue-touch-ripple#20]
<div @click="test()">
      <vue-touch-ripple></vue-touch-ripple>
</div>

**Comment by lizhenggan** [comment]
<div @click="test">
   <vue-touch-ripple></vue-touch-ripple>
</div>

**Comment by lizhenggan** [comment]
"<div @click='test()'>
<vue-touch-ripple></vue-touch-ripple>
</div>"

**Comment by lizhenggan** [comment]
<div @click="test()">
    <touch-ripple :speed="1" :opacity="0.3" color="#fff" transition="ease">
      点我
    </touch-ripple>
  </div>

**Comment by lizhenggan** [comment]
> <div @click="test()">
    <touch-ripple :speed="1" :opacity="0.3" color="#fff" transition="ease">
      点我
    </touch-ripple>
  </div>

**Comment by lizhenggan** [comment]
`<div @click="test()"><touch-ripple :speed="1" :opacity="0.3" color="#fff" transition="ease">点我</touch-ripple></div>`

**Comment by cocody** [comment]
在内层加入事件吧

**Comment by surmon-china** [comment]
if you expect to bind more flexible events on the component, [in Vue3 you can just bind the events directly, instead of using the @xxx.native modifier in Vue2](https://v3-migration.vuejs.org/breaking-changes/v-on-native-modifier-removed.html).
