### ISSUE TITLE
How to use v-touch-Ripple and  @click instruments to use？

### ISSUE THREAD

**Issue by Myrrosego** [surmon-china/vue-touch-ripple#21]
How to use v-touch-Ripple and  @click instruments to use？

**Comment by surmon-china** [comment]
if you expect to bind more flexible events on the component, [in Vue3 you can just bind the events directly, instead of using the @xxx.native modifier in Vue2](https://v3-migration.vuejs.org/breaking-changes/v-on-native-modifier-removed.html).
