### ISSUE TITLE
How to use '@click instruments' with 'v-touch-ripple' to use？

### ISSUE THREAD

**Issue by 2ju2** [surmon-china/vue-touch-ripple#27]
How to use '@click instruments' with 'v-touch-ripple' to use？

ex) 
<touch-ripple @click="anotherMethod">click me<touch-ripple> 
<a is="touch-ripple" @click="anotherMethod">click me<a>

Those "@click" not working!

**Comment by surmon-china** [comment]
@2ju2 use `@click.native` .
