### ISSUE TITLE
Vue 3 Support

### ISSUE THREAD

**Issue by jd-solanki** [surmon-china/vue-touch-ripple#28]
As Vue 3 has RC It will be a good idea to add support for Vue 3.

Currently, if we use this package with Vue 3 we are getting error.

![image](https://user-images.githubusercontent.com/47495003/93464555-f728fd00-f906-11ea-86a7-f0d3730093da.png)

**Comment by ejirocodes** [comment]
Hi @jd-0001, @surmon-china I just released the support for Vue 3 [here](https://www.npmjs.com/package/vue3-touch-ripple)

**Comment by surmon-china** [comment]
[v4.0.0](https://github.com/surmon-china/vue-touch-ripple/tree/v4.0.0) released.
