### ISSUE TITLE
滑动问题

### ISSUE THREAD

**Issue by w550** [surmon-china/vue-touch-ripple#4]
当作用在 多条列表上的时候
滚动的时候会触发效果
应该做个判断。

 <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
 <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
 <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>
  <li v-touch-ripple></li>

**Comment by surmon-china** [comment]
稍后我测试

**Comment by surmon-china** [comment]
问题已解决，请升级至v2.3.0
