### ISSUE TITLE
有没有办法通过引入js的方式直接使用呢？

### ISSUE THREAD

**Issue by Molunerfinn** [surmon-china/vue-touch-ripple#5]
项目这边其他人都是非node技术栈，很难说服用import、webpack、require并且还要编译成es5的js，所以能否提供像Vue.js一样直接在页面中的script标签src="vue-touch-ripple.min.js"这样的方式来使用呢？感谢开发者~

**Comment by surmon-china** [comment]
可以，下个版本更新

**Comment by Molunerfinn** [comment]
Thx ：)
