### ISSUE TITLE
vue-cli npm run build 错误

### ISSUE THREAD

**Issue by ChobitsSP** [surmon-china/vue-touch-ripple#6]
ERROR in static/js/vendor.c97fad4c6740d5d63c37.js from UglifyJs
SyntaxError: Unexpected token: name (touchs) [./~/.npminstall/vue-touch-ripple/2.3.0/vue-touch-ripple/touchripple.js:97,0]

vue 2.0

**Comment by ChobitsSP** [comment]
https://github.com/joeeames/WebpackFundamentalsCourse/issues/3#issuecomment-165139603

**Comment by surmon-china** [comment]
请升级到最新版再试一下，我这边尝试做了一些修复。

**Comment by throrin19** [comment]
This is the error with the latest version : 

```
SyntaxError: Unexpected token: operator (>) [./~/vue-touch-ripple/touchripple.js:99,0][vendor.76c788f4.js:1922,22] 
```
