### ISSUE TITLE
ios 延迟

### ISSUE THREAD

**Issue by w550** [surmon-china/vue-touch-ripple#7]
体验式感觉不是 touch 事件 像是 click事件。
延迟半拍
尤其是 如果这个 按钮是 a 标签需要跳转的时候。动画根本就放不完就跳转了。

**Comment by w550** [comment]
https://github.com/AlloyTeam/AlloyTouch/wiki/AlloyTouch-Button%E6%8F%92%E4%BB%B6-%E4%B8%8D%E5%86%8D%E6%84%81click%E5%BB%B6%E8%BF%9F%E5%92%8C%E7%82%B9%E5%87%BB%E6%80%81

可以根据这个案例优化

**Comment by surmon-china** [comment]
童鞋你说的对，现在已经没有touch事件了；
1：因为touch事件在移动端没有办法判断touchstart和touchmove，所以touch事件会造成效果不佳，例如你手指放在某个元素上去滑动屏幕，结果这个元素触发效果了，这就不是想要的（当然我确实没有深入去解决这个问题）
2：经测试，click事件可以原生地做到把touch和move区别开来，缺点就是有300ms延时

我刚看到了你留的链接，我会抽时间看下，尽可能做进一步优化

**Comment by w550** [comment]
@surmon-china 
赞
