### ISSUE TITLE
Vue warn when using "v-touch-ripple" ?

### ISSUE THREAD

**Issue by cuduy197** [surmon-china/vue-touch-ripple#9]
Property or method "ripple" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

**Comment by surmon-china** [comment]
If you need to "v-touch-ripple" this way to use, you need to use the global use to register, `Vue.use(VueTouchRipple)`, you do so？

**Comment by cuduy197** [comment]
Oh, sorry my bad, i'm using pug template.
when i add like this is will show warn: 
`f7-button.link.open-popover(v-touch-ripple)`
To fix it : 
`f7-button.link.open-popover(v-touch-ripple='')`
Thanks you for very nice plugin for Vue ^^

**Comment by surmon-china** [comment]
https://github.com/vuejs/vue-loader/issues/693
Is this question like this, is this question helpful to you?

**Comment by cuduy197** [comment]
Thanks you :tada:

**Comment by surmon-china** [comment]
Ok, then the problem is temporarily closed, there are new problems can be reopened.

**Comment by MerlinAhh** [comment]
你好, 我在全局注册了Vue.use(VueTouchRipple), 但是用在button上点击直接报错了
![image](https://user-images.githubusercontent.com/31106608/55124124-1bf04a00-5140-11e9-8f0d-3cd0d4102013.png)
![image](https://user-images.githubusercontent.com/31106608/55124134-26124880-5140-11e9-9a92-294001ee8382.png)
